language: java
jdk:
  - oraclejdk8
 addons:
  sonarcloud:  "mcprog-github"
    token:
      secure: SONAR_TOKEN
script: ant build

  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
