language: java
jdk:
  - oraclejdk8
script:
  - mvn package
  mvn sonar:sonar \
    -Dsonar.projectKey=mcprog_TestTravis \
      -Dsonar.organization=mcprog-github \
        -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

